# Generated by Django 3.2.9 on 2023-02-18 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('final', '0003_courses'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
