# Generated by Django 3.2.9 on 2023-02-19 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('final', '0004_category_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='image',
        ),
    ]
