# Generated by Django 3.2.9 on 2023-02-22 12:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('final', '0006_auto_20230219_2019'),
    ]

    operations = [
        migrations.AddField(
            model_name='cards',
            name='score',
            field=models.IntegerField(choices=[(10, 'Easy'), (6, 'Medium'), (2, 'Hard')], default=10),
        ),
        migrations.AlterField(
            model_name='cards',
            name='front_side',
            field=models.CharField(max_length=512),
        ),
        migrations.CreateModel(
            name='UserChoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='final.cards')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
