# Generated by Django 3.2.9 on 2023-02-22 14:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('final', '0007_auto_20230222_1259'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cards',
            name='score',
        ),
        migrations.AlterField(
            model_name='userchoice',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card', to='final.cards'),
        ),
        migrations.AlterField(
            model_name='userchoice',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
    ]
