# Generated by Django 3.2.9 on 2023-02-22 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('final', '0008_auto_20230222_1444'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='scoreSum',
            field=models.IntegerField(default=0),
        ),
    ]
