# Generated by Django 3.2.9 on 2023-02-22 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('final', '0009_user_scoresum'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cards',
            name='title',
        ),
    ]
