# Generated by Django 3.2.9 on 2023-02-22 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('final', '0010_remove_cards_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='cards',
            name='title',
            field=models.CharField(blank=True, max_length=16),
        ),
    ]
