# Generated by Django 3.2.9 on 2023-02-23 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('final', '0013_remove_userchoice_solved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cards',
            name='title',
        ),
        migrations.AlterField(
            model_name='cards',
            name='back_side',
            field=models.CharField(max_length=512),
        ),
    ]
